---
# Source: superset-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-operator-deployment
  labels:
    helm.sh/chart: superset-operator-0.3.0
    app.kubernetes.io/name: superset-operator
    app.kubernetes.io/instance: superset-operator
    app.kubernetes.io/version: "0.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: superset-operator
      app.kubernetes.io/instance: superset-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: superset-operator
        app.kubernetes.io/instance: superset-operator
    spec:
      serviceAccountName: superset-operator-serviceaccount
      securityContext:
        {}
      containers:
        - name: superset-operator
          securityContext:
            {}
          image: "docker.stackable.tech/stackable/superset-operator:0.3.0"
          imagePullPolicy: IfNotPresent
          resources:
            {}
          volumeMounts:
            - mountPath: /etc/stackable/superset-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: superset-operator-configmap
