---
apiVersion: v2
name: superset-operator
version: 0.3.0
appVersion: "0.3.0"
description: The Stackable Operator for Apache Superset
home: https://github.com/stackabletech/superset-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
