[package]
name = "stackable-superset-operator"
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Stackable Operator for Apache Superset"
license = "OSL-3.0"
version = "0.3.0-nightly"
edition = "2021"
repository = "https://github.com/stackabletech/superset-operator"

[dependencies]
anyhow = "1.0"
clap = "2.34"
fnv = "1.0"
futures = { version = "0.3", features = ["compat"] }
serde = "1.0"
serde_yaml = "0.8"
snafu = "0.6"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.6.0" }
stackable-superset-crd = { path = "../crd" }
structopt = "0.3"
tokio = { version = "1.15", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"

[build-dependencies]
built = { version =  "0.5", features = ["chrono", "git2"] }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.6.0" }
stackable-superset-crd = { path = "../crd" }
