[package]
authors = ["Lars Francke <lars.francke@stackable.de>"]
description = "Stackable Operator for Apache Superset"
edition = "2018"
license = "OSL-3.0"
name = "stackable-superset-operator-binary"
repository = "https://github.com/stackabletech/superset-operator"
version = "0.1.0-nightly"
build = "build.rs"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", branch = "main" }
stackable-superset-crd = { path = "../crd" }
stackable-superset-operator = { path = "../operator" }

clap = "2.33"
tokio = { version = "1.10", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"

[build-dependencies]
built = { version =  "0.5", features = ["chrono", "git2"] }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", branch = "main" }
stackable-superset-crd = { path = "../crd" }

[package.metadata.deb]
name = "stackable-superset-operator"
maintainer-scripts = "../../packaging/debian/"
systemd-units = { enable = false, unit-name = "stackable-superset-operator" }
assets = [
    ["../../target/release/stackable-superset-operator", "opt/stackable/superset-operator/", "755"],
    ["../../deploy/crd/supersetcluster.crd.yaml", "etc/stackable/superset-operator/crd/", "644"],
    ["../../deploy/config-spec/properties.yaml", "etc/stackable/superset-operator/config-spec/", "644"],
]

[[bin]]
name = "stackable-superset-operator"
path = "src/stackable-superset-operator.rs"
