[workspace]
members = ["rust/crd", "rust/operator-binary"]

# [patch."https://github.com/stackabletech/operator-rs.git"]
# stackable-operator = { path = "path/to/operator-rs" }
# stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", branch = "your/feature/branch" }
