version: 0.1.0
spec:
  units: []
properties:
  - property: &credentialsSecret
      propertyNames:
        - name: "credentialsSecret"
          kind:
            type: "env"
      datatype:
        type: "string"
      roles:
        - name: "node"
          required: true
      asOfVersion: "0.0.0"
      description: "The secret where the Superset credentials are stored."
  - property: &rowLimit
      propertyNames:
        - name: "ROW_LIMIT"
          kind:
            type: "file"
            file: "superset_config.py"
      datatype:
        type: "integer"
      defaultValues:
        - fromVersion: "0.0.0"
          value: "50000"
      recommendedValues:
        - fromVersion: "0.0.0"
          value: "50000"
      roles:
        - name: "node"
          required: false
      asOfVersion: "0.0.0"
      description: "Row limit when requesting chart data. Corresponds to ROW_LIMIT"
